Add: modeling
wecode-bootcamp-korea/32-1st-sulsajo-backend pull request #1
Opened 2022-04-26 07:48 UTC by alexms0316

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- models.py 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. models.py 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-26 08:17 UTC, kyeongraekim requested changes

2022-04-26 08:17 UTC, kyeongraekim commented on products/models.py
> +    alcohol_degree = models.ForeignKey('alcohol', on_delete=models.CASCADE)
- 정렬 컨벤션 한 번 신경써 주세요
- alcohol이 소문자로 작성되어있는데 외래키가 잘 물리나요?  makemigration 해서 정상 작동 유무를 확인 하신 후에 푸시하는것을 잊지 말아주세요~

2022-04-26 08:17 UTC, kyeongraekim commented on products/models.py
> +    price       = models.DecimalField(max_length=100000)
decimal field속성에서는  max_digit과 decimal_places설정을 꼭 주세요~ 이 설정이 어떠한 역할과 기능을 하는지 꼭 살펴보세요!~ 공식문서를 참고하시면 max_length에 대한 설정이 불가함을 확인하실수 있으실 겁니다.

2022-04-26 08:17 UTC, kyeongraekim commented on products/models.py
> +class Product_Image(models.Model):
Class명은 컨벤션상 CamelCase로 작성해주세요

2022-04-26 08:17 UTC, kyeongraekim commented on products/models.py
> +    product    = models.ForeignKey('Product', on_delete=models.CASCADE)
어떤 부분은 클래스로, 어떤 부분은 문자열로 잡아주셨네요 해당 부분의 기능의 차이점을 혹시 아시나요?

2022-04-26 08:17 UTC, kyeongraekim commented on products/models.py
> +    Finger_food   = models.ForeignKey('Finger_food', on_delete=models.CASCADE)
파이썬 변수명에 대문자는 와서는 안됩니다.

2022-04-26 08:17 UTC, kyeongraekim commented
그리고 PR Template 형식에 맞게 학습하신 부분들 꼭 상세히 기록해주세요! 그만큼 휘발성 강한 지식들이 최대한 오래 남을 수 있습니다.

2022-04-26 11:32 UTC, CHEESECHOUX commented on products/models.py
> +    alcohol_degree = models.ForeignKey('alcohol', on_delete=models.CASCADE)
넵! 알겠습니다!

2022-04-26 11:35 UTC, CHEESECHOUX commented on products/models.py
> +    price       = models.DecimalField(max_length=100000)
저희는 금액을 최대 100,000원으로 구현할 예정이라 max_digit=6 그리고 decimal_place를 소수점 둘째자리로 하기위해 2로 했습니다!

2022-04-26 11:35 UTC, CHEESECHOUX commented on products/models.py
> +class Product_Image(models.Model):
넵! image가 중요하다고 생각하여 product_Image 로 수정하였습니다!

2022-04-26 11:51 UTC, CHEESECHOUX commented on products/models.py
> +    product    = models.ForeignKey('Product', on_delete=models.CASCADE)
해당 클래스가 윗쪽에서 선언되지 않은 경우 따옴표를 사용하여 지정해줍니다!

2022-04-26 11:51 UTC, CHEESECHOUX commented on products/models.py
> +    Finger_food   = models.ForeignKey('Finger_food', on_delete=models.CASCADE)
넵!

2022-04-26 11:52 UTC, CHEESECHOUX commented
네 알겠습니다! 감사합니다!

2022-04-27 09:12 UTC, bigfanoftim requested changes

2022-04-27 09:12 UTC, bigfanoftim commented on products/models.py
> +    timestamp  = models.DateTimeField(auto_now_add=True)
생성일자를 담으려는 의도가 맞을까요?
```suggestion
    created_at  = models.DateTimeField(auto_now_add=True)
```

2022-04-27 09:17 UTC, CHEESECHOUX commented on products/models.py
> +    timestamp  = models.DateTimeField(auto_now_add=True)
네 맞습니다! created_at을 사용하였다가 timestamp를 사용해보고 싶어 수정하였습니다.

2022-04-27 09:37 UTC, kyeongraekim approved these changes
LGTM!~ 추후 모델링 수정 기획이 생기면 새로운 feature 모델링 브랜치를 파서 푸시해주세요~

2022-04-27 09:37 UTC, merged