[signup, login]
wecode-bootcamp-korea/32-1st-sulsajo-backend pull request #2
Opened 2022-04-28 08:52 UTC by CHEESECHOUX

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 회원가입 및 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. bcrypt로 회원가입 비밀번호 암호화 적용 
2. 로그인시 token 발급 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- validation.py 모듈을 적용시켜보았습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-04-28 10:05 UTC, kyeongraekim requested changes

2022-04-28 10:05 UTC, kyeongraekim commented on users/validation.py
> +            raise ValidationError('INVALID_PASSWORD')
각각의 개별 행동을 하는 함수만을 담기 위해서 클래스를 선언하는 것은 조금 소모적일 수 있습니다. 보다 클래스 다운 모습으로 사용할 계획이  아니라면 개별 함수로 존재해도 괜찮을 것 같습니다!

2022-04-28 10:05 UTC, kyeongraekim commented on users/views.py
> +                email     = data['email'],
위에 변수에 선언해주신 email을 활용하는게 이곳에서 중복 매핑하는 것보다 더 효율적일 것 같네요!

2022-04-28 10:05 UTC, kyeongraekim commented on users/views.py
> +
jsondecode error가 어떤 것인지 한 번 리서치 해주시고 종종 일어날 수 있는 예외 상황인 것을 감안하여 이곳에 예외문으로 넣어주세요!

2022-04-28 10:05 UTC, kyeongraekim commented on users/views.py
> +            access_token    = jwt.encode({'id':user.id}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
생성해주시는 토큰에 만료기한도 한 번 추가해보시는 것은 어떨까요?

2022-04-28 11:20 UTC, gsoosuu commented on users/validation.py
> +            raise ValidationError('INVALID_PASSWORD')
넵 수정하겠습니다!

2022-04-28 11:32 UTC, CHEESECHOUX commented on users/views.py
> +            access_token    = jwt.encode({'id':user.id}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
넵! 추가 하겠습니다!

2022-04-29 07:28 UTC, kyeongraekim requested changes

2022-04-29 07:28 UTC, kyeongraekim commented on users/validation.py
> +def password_validate(value):
가독성을 위해서 두 함수에 공백을 주어 띄어주세요~

2022-04-29 07:30 UTC, kyeongraekim commented
로그인 데코레이터 함수도 함께 다음 푸시떄 올려주세요~

2022-04-29 09:11 UTC, CHEESECHOUX commented
수정 완료 하였습니다!

2022-04-29 09:50 UTC, kyeongraekim requested changes

2022-04-29 09:50 UTC, kyeongraekim commented on products/models.py
> +    checked = models.BooleanField(default=True)
불리언필드의 변수명은 is_checked 로 보다 명확하게 영문으로 표현합니다~

2022-04-29 09:50 UTC, kyeongraekim commented on products/models.py
>      product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True)
foreignkey는 blank = True 말고 nullable 하게 진행해주세요

2022-04-29 09:50 UTC, kyeongraekim commented on products/models.py
order와 cart가 서로 연결이 되어있어야 할 것 같네요! 장바구니에서 주문으로 넘어가는 내용이 없네요~

2022-04-29 09:50 UTC, kyeongraekim commented on products/models.py
> +    count   = models.IntegerField()
음수가 진행될 수 없으니 positiveIntegerField() 로 한 번 고려해보세요

2022-05-01 07:08 UTC, kyeongraekim approved these changes
LGTM!~

2022-05-01 07:08 UTC, merged