Feature/detail
wecode-bootcamp-korea/32-1st-sulsajo-backend pull request #3
Opened 2022-05-03 09:37 UTC by alexms0316

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- products.views에서 상세페이지 관련 view 작성 & 구독페이지 관련 view 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
products app내 view.py 작성
- 상세페이지 view작성하면서 코드리뷰 반영 부분 수정
- 구독페이지 view작성하는중 JSON Serializable 오류 관련 수정 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 모델링의 중요성에 대해 뼈져리게 느꼈습니다. 다음 협업시부턴 프론트엔드분들과 모델링 작성시 소통을 많이해야할 것 같습니다. 
- 정참조와 역참조 관련하여 select_related, prefetch_related, _set 사용 차이에 대해 알게 되었습니다.
- 코드를 작성함에 있어서 다른이의 코드를 참고하는 것은 좋으나, 코드를 한줄한줄 이해를하며 설명을 할 줄 알아야 할 것 같습니다. 

<br />

## :: 기타 질문 및 특이 사항

2022-05-03 09:46 UTC, kyeongraekim requested changes

2022-05-03 09:46 UTC, kyeongraekim commented on .gitignore
> +users.csv
*.csv 형식으로 하시면 더 편하게 모든 csv를 깃 이그노어에 추가하실 수 있습니다~

2022-05-03 09:46 UTC, kyeongraekim commented on products/urls.py
> +    path('/subscribe/<int:product_id>', SubscribeView.as_view())
- detail이란 단어는 전체 다 제거해주셔도 될 것 같네요! 그리고 RESTful 한 설계 규칙에 맞게 동사형 어미는 다 없애주세요
- View클래스의 명칭도 해당 CommentView내부에서 delete란 메소드로 접근하는 것이니 삭제해주세요

2022-05-03 09:46 UTC, kyeongraekim commented on products/views.py
> +                    } for product in products]
이 부분은 전체 리스트의 마지막 종결 부분이기 떄문에 가독성향상을 위해서 인덴테이션은 하나 앞으로 빼주세요~

2022-05-03 09:46 UTC, kyeongraekim commented on products/views.py
> +class DetailProductView(View):
클래스 명에 Detail은 verbose하게 느껴지네요~

2022-05-03 09:46 UTC, kyeongraekim commented on products/views.py
> +class DetailCommentDeleteView(View):
위 CommentView를 하나로 선언해주시고 이하 시점에서의 분기는 post, delete 등 메소드 별로 될 수 있게 하나의 클래스에 넣어주세요!~

2022-05-03 09:46 UTC, kyeongraekim commented on products/views.py
> +            return JsonResponse({'message':'SUCCESS'}, status=200)
생성이 정상적으로 된다면 201 상태코드가 더 맞겠네요!~

2022-05-03 09:46 UTC, kyeongraekim commented on products/views.py
> +        return JsonResponse({'message': 'SUCCESS'}, status=200)
삭제에 대한 메소드는 204가 맞겠네요!~

2022-05-03 09:46 UTC, kyeongraekim commented on products/views.py
> +            "message" : '구독페이지 제품 관련 데이터',
메시지는 영문 메세지로 간단한게 작성해주세요~

2022-05-03 09:46 UTC, kyeongraekim commented on products/views.py
> +        except Product.DoesNotExist:
Product.DoesNotExist에러의 처리내용과 아래 ValueError가 서로 안맞느것 같아보이네요!~

2022-05-03 09:46 UTC, kyeongraekim commented on products/views.py
> +            category_image = CategoryImage.objects.get(id=1)
현재 아이디 값이 하드 코딩되어있습니다. 깃헙에 올라오는 내용에 대한 하드코딩은 꼭 기피해주세요!

2022-05-03 09:46 UTC, kyeongraekim commented on products/views.py
> +            )
이 부분은 수정 반영 전의 지수님 코드처럼 보여지네요!

2022-05-03 09:46 UTC, kyeongraekim commented on requrements.txt
> +wheel               0.37.1
저번에 말씀드렸듯이 freeze 형태가 올라와야합니다.

2022-05-03 12:00 UTC, alexms0316 commented on products/views.py
> +class DetailProductView(View):
수정 완료하였습니다!

2022-05-03 12:00 UTC, alexms0316 commented on products/views.py
> +class DetailCommentDeleteView(View):
수정완료 하였습니다!

2022-05-03 12:24 UTC, alexms0316 commented on products/views.py
> +            "message" : '구독페이지 제품 관련 데이터',
수정완료 하였습니다

2022-05-03 12:26 UTC, alexms0316 commented on products/views.py
> +        except Product.DoesNotExist:
수정완료 하였습니다

2022-05-03 12:29 UTC, alexms0316 commented on products/views.py
> +            category_image = CategoryImage.objects.get(id=1)
해당 내용은 삭제하였습니다

2022-05-03 12:29 UTC, alexms0316 commented on products/views.py
> +            )
삭제완료하였습니다!

2022-05-03 12:30 UTC, alexms0316 commented on requrements.txt
> +wheel               0.37.1
넵 수정완료 하였습니다!!

2022-05-04 06:38 UTC, kyeongraekim requested changes

2022-05-04 06:38 UTC, kyeongraekim commented on products/views.py
> +from json.decoder     import JSONDecodeError
json 에서 import 하신 부분은 더 상단에 위치해야 될 것 같네요!~

2022-05-04 06:38 UTC, kyeongraekim commented on products/views.py
> +from json.decoder     import JSONDecodeError
컨벤션 정렬 더 유심히 신경써주세요

2022-05-04 06:38 UTC, kyeongraekim commented on products/views.py
> +            return JsonResponse({'message':'VALUE_ERROR'}, status = 404)
상품이 존재하지 않을 때의 에러가 위 코드에서 나지 않습니다.
그리고 value_error라고 한 부분이랑 서로 상응하는 내용은 아닌 것처럼 보이네요!

2022-05-04 06:38 UTC, kyeongraekim commented on products/views.py
> +        if user != comment.user:
이 부분은 위 80 번째 filter() 부분에 중복으로 걸어줄 수 있는 조건처럼 보이네요!

2022-05-04 06:38 UTC, kyeongraekim commented on products/views.py
> +        Comment.objects.filter(id=comment.id).delete()
filter로 잡혀서 쿼리셋으로 반환된 내용을 바로 삭제하기가 불가능할 것 같은데 혹시 이 부분은 작동하는 코드인가요?

2022-05-04 06:38 UTC, kyeongraekim commented on products/views.py
> +            created_at   = data.get('created_at', None)
comment 생성 post 함수인데 created_at을 변수에 담아주시는 이유가 불분명하네요! timestampmodel로 혹시 모델에 적용이 안되어 있는 걸까요?

2022-05-04 06:49 UTC, alexms0316 commented on products/views.py
> +from json.decoder     import JSONDecodeError
넵 수정 완료하였습니다.

2022-05-04 07:07 UTC, alexms0316 commented on products/views.py
> +        Comment.objects.filter(id=comment.id).delete()
확인해본 결과 작동하지 않는 것 같습니다

2022-05-04 07:08 UTC, alexms0316 commented on products/views.py
> +        Comment.objects.filter(id=comment.id).delete()
수정하도록 하겠습니다

2022-05-04 07:08 UTC, alexms0316 commented on products/views.py
> +            created_at   = data.get('created_at', None)
삭제 완료하였습니다!!

2022-05-04 09:18 UTC, kyeongraekim approved these changes
LGTM!~

2022-05-04 09:18 UTC, merged